apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
  namespace: argocd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
        - name: argocd-demo
          image: salmansbab94/argocd-demo-app:12
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
